name: 🚀 Deploy | get.rso.dev
run-name: 🚀 Deploy | ${{ github.run_number }} | by @${{ github.actor }} | ${{ github.event_name}}

#######################################################
# Version: 0.0.2
#######################################################
# TODO: Optimize triggers.
# TODO: Add a job to build README files.
# TODO: Add malicious code scanner.
# TODO: Add a CR LF formatter.
#######################################################
# NOTE:
# This workflow uploads/syncs the files a remote FTP server.
#######################################################

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
    - '.templates/**'
    - '.github/**'
    - '.gitignore'
    - 'README.md'
    - 'LICENSE.md'

  workflow_dispatch:

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Get Codebase
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          protocol: ftp
          local-dir: ./
          server-dir: ./
          state-name: .ftp-deploy-sync-state.json
          dangerous-clean-slate: false
          exclude: .git,.github,.gitignore,.gitattributes,.gitmodules,.gitkeep,.DS_Store,.vscode,.idea,.sourcemaps,.vs,.nyc_output,.nycrc,.nycrc.json,.nycrc.yml,.nycrc.yaml,.nycrc.js,.nycrc.cjs

      - name: Purge CF Cache
        uses: jakejarvis/cloudflare-purge-action@v0.3.0
        env:
            CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
            CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
